@E_Commerce.Web_HostAddress = http://localhost:5100

GET {{E_Commerce.Web_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{E_Commerce.Web_HostAddress}}/api/Products

###
@id=10
GET {{E_Commerce.Web_HostAddress}}/api/Products/{{id}}